### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by QuantumToasted** [ErwanTLG/Challonge.Net#1]
Sorry to be a bother. It would be __greatly__ appreciated for a NuGet package to be published. The *only* Challonge API wrapper on NuGet currently, [ChallongeSharp](https://www.nuget.org/packages/ChallongeSharp/), is an actually broken package. Entire classes are empty that shouldn't be, classes missing methods, the whole shebang. Between it being a relatively old package and the maintainer being nigh impossible to contact, this would be a breath of fresh air.

**Comment by ErwanTLG** [comment]
Currently the wrapper is in early developpement, it is still full of bugs and some features are missing (like the Attachments functionnalities), and other are only half-way implemented (some of the tournament-related ones). Also, I haven't done much testing (which is currently my focus). I don't want to publicly release a NuGet package in this state of developpement. You can still download the entire project and create a private NuGet package on your machine, and linking this one to your project.

To do so, in VS, right click on the project, then pack. This will create a nupkg file. To link it to your other project, choose manage NuGet packages, then (still on VS), you can select a package source (on the top-right). You probably will have to create a new package source. Simply enter the path to the folder where the nupkg file is located, and it should appear in the browse tab.
If you are using some other IDE, google might help you better than I do.

**This is the current work-around, but a package will be published once the project is a bit more stable**

**Comment by QuantumToasted** [comment]
I'm aware of how to pack a project manually, I just always prefer first-party packages to doing it myself! Thank you anyways for the quick response.

**Comment by ErwanTLG** [comment]
A package is now available here : 
https://www.nuget.org/packages/Challonge.Net/1.0.0-beta.1
