### ISSUE TITLE
Question/bug: What is the purpose of JsonDateTimeConverter?

### ISSUE THREAD

**Issue by QuantumToasted** [ErwanTLG/Challonge.Net#4]
I've encountered issues with this library involving [JsonDateTimeConverter](https://github.com/ErwanTLG/Challonge.Net/blob/master/Challonge.Net/JsonDateTimeConverter.cs) where it would state that it could not properly deserialize the provided value. Commenting out the class and all its usages fixed this problem entirely on my local fork (Newtonsoft.Json can properly deserialize `DateTimeOffset?` just fine out of the box), and the values Challonge provides via the API properly deserialize to a DTO, **including the proper timezone/offset**. Was it created to solve an issue with data the API used to return but no longer does?

**Comment by ErwanTLG** [comment]
I had some issues when I first started this project, probably because I started using `DateTime` instead of `DateTimeOffset`. I did as you said, and everything now seems to work fine, so thank you for reporting this. I just made a commit with the mentioned changes.
